### ISSUE TITLE
Detox test setup

### ISSUE THREAD

**Issue by ManulParihar** [Blockchain-Powered-eSIM/LPA#41]
PR: https://github.com/Blockchain-Powered-eSIM/LPA/pull/42

* Basic Detox setup for end to end testing
* Add tests
* Write build script to update config of mmkv-storage library

**Comment by ManulParihar** [comment]
* Build command: `detox build --configuration android.emu.debug`
* Test command: `detox test --configuration android.emu.debug`

**Comment by GuyPhy** [comment]
https://github.com/Blockchain-Powered-eSIM/LPA/issues/46#issuecomment-2050698893

This is the current status for the issue, the error hit when running `detox test --configuration android.emu.debug` needs to be resolved. Next action item would be unit test integration

**Comment by ArpitxGit** [comment]
The error mention there are no modules find as mentioned in `jest.config.fs` in e2e:

```
/** @type {import('@jest/types').Config.InitialOptions} */
module.exports = {
  rootDir: '..',
  testMatch: ['<rootDir>/e2e/**/*.test.js'],
  testTimeout: 120000,
  maxWorkers: 1,
  globalSetup: 'detox/runners/jest/globalSetup',
  globalTeardown: 'detox/runners/jest/globalTeardown',
  reporters: ['detox/runners/jest/reporter'],
  testEnvironment: 'detox/runners/jest/testEnvironment',
  verbose: true,
};

const baseConfig = require("../base.jest.config.js");

module.exports = {
  ...baseConfig,
  setupFilesAfterEnv: ["./init.ts"],
  setupFiles: [
    "<rootDir>/../../../node_modules/react-native/jest/setup.js",
    "<rootDir>/../../../node_modules/react-native-gesture-handler/jestSetup.js",
    "<rootDir>/../../../test/setup.ts",
  ],
  testPathIgnorePatterns: ["/node_modules/"],
};
```

**Comment by ArpitxGit** [comment]
- there is no `setup.js` in `node_modules/react-native/jest` 
- there is no `react-native-gesture-handler` in `node_modules`
- there is no `test` file in root directory

**Comment by ArpitxGit** [comment]
error resolved, Detox tests are now running and communicating, the verification is it indicated by the WebSocket (ws) messages between the Detox server and client.
what's happening and what need to check next:

WebSocket Messages:
ws-server get data: The server receives a request to check if the app is ready (isReady).
ws-server send data: The server is sending a response or forward another isReady check.
ws-client send message: The client sends a message back, possibly indicating its current status or asking for the next instruction.

using `detox test --configuration android.emu.debug --loglevel trace` helps identify at which point the interaction fails or stalls, giving more insight into whether the issue lies with the app's readiness or the test setup.

updated [codebase](https://github.com/ArpitxGit/LPA)

**Comment by ArpitxGit** [comment]
The detox setup is tested now , the next is to write specific test cases and test them manually using emulator.
Keeping this test setup and testing using emulator for now.

**Comment by ArpitxGit** [comment]
test cases:  

- [x] App Launch Test
- [x] Modal Visibility Test
- [x] Unique ID Fetch Test
- [x] Modal Dismissal Test

`npm run` :

```
> LPAapp@0.0.1 test
> detox test --configuration android.emu.debug

09:34:03.799 detox[78599] B jest --config e2e/jest.config.js
09:34:06.951 detox[78600] i firstTest.spec.js is assigned to emulator-5554 (Pixel_3a_API_34_extension_level_7_arm64-v8a)
09:34:06.953 detox[78600] i App Launch Test: should launch the app successfully
09:34:09.312 detox[78600] i App Launch Test: should launch the app successfully [OK]

09:34:09.313 detox[78600] i Modal Visibility Test: should initially hide the modal
09:34:09.444 detox[78600] i Modal Visibility Test: should initially hide the modal [OK]

09:34:09.445 detox[78600] i Unique ID Fetch Test: should fetch and display unique ID in modal
09:34:10.922 detox[78600] i Unique ID Fetch Test: should fetch and display unique ID in modal [OK]

09:34:10.924 detox[78600] i Modal Dismissal Test: should dismiss the modal when "Back" button is pressed
09:34:12.092 detox[78600] i Modal Dismissal Test: should dismiss the modal when "Back" button is pressed [OK]

 PASS  e2e/firstTest.spec.js (7.712 s)
  App Launch Test
    ✓ should launch the app successfully (2358 ms)
  Modal Visibility Test
    ✓ should initially hide the modal (131 ms)
  Unique ID Fetch Test
    ✓ should fetch and display unique ID in modal (1476 ms)
  Modal Dismissal Test
    ✓ should dismiss the modal when "Back" button is pressed (1167 ms)

Test Suites: 1 passed, 1 total
Tests:       4 passed, 4 total
Snapshots:   0 total
Time:        7.783 s, estimated 8 s
Ran all test suites.
```

**Comment by ArpitxGit** [comment]
added e2e/README.md to guiding through tests

**Comment by ArpitxGit** [comment]
closing this issue since unit tests is merged, here's the [PR](https://github.com/Blockchain-Powered-eSIM/LPA/pull/62) .
