### ISSUE TITLE
MMKV build script

### ISSUE THREAD

**Issue by ArpitxGit** [Blockchain-Powered-eSIM/LPA#46]
Write a build script which updates the `@node_modules/react-native-mmkv-storage/android/build.gradle` file with the following code:
```
android {
   // existing code
   packagingOptions {
        pickFirst '**/libc++_shared.so'
        pickFirst '**/libfbjni.so'
    }
}
```
> Make sure that the `packagingOptions` is added inside the already existing android object. The build script should not create a new android object.

**Comment by ArpitxGit** [comment]
Make following changes in the `package.json` file:
```
...
"scripts": {
    "test": "detox test --configuration android.emu.debug",
    "build": "./mmkv-build-script.sh && detox build --configuration android.emu.debug",
    "watch": "tsc --watch"
  },
```
> where, `mmkv-build-script.sh` file contains the script to update the mmkv storage library

**Comment by GuyPhy** [comment]
The command `detox build --configuration android.emu.debug` works now, along with the integration of `npm run build`

Working on resolving the error for `detox test --configuration android.emu.debug` or `npm run test`

The error message 
```
04:26:39.010 detox[58532] B jest --config e2e/jest.config.js
● Validation Error:

  Module <rootDir>/../../../node_modules/react-native/jest/setup.js in the setupFiles option was not found.
         <rootDir> is: /Users/guyphy4/GMMS/AppDev/ethLPA/e2e

  Configuration Documentation:
  https://jestjs.io/docs/configuration

04:26:39.136 detox[58532] E Command failed with exit code = 1:
jest --config e2e/jest.config.js
```
