### ISSUE TITLE
Securely store and access keystore

### ISSUE THREAD

**Issue by ArpitxGit** [Blockchain-Powered-eSIM/LPA#51]
Use android [keystore](https://developer.android.com/privacy-and-security/keystore) to securely store and access ECDSA generator via KMM

**Comment by GuyPhy** [comment]
Using the KMM.jar file [here](https://github.com/Blockchain-Powered-eSIM/LPA/blob/jar/android/app/libs/KMM.jar), the EC key pair is generated and then needs to be stored in the android keystore, I have added methods to store the the generated key using [keyStore.setEntry](https://developer.android.com/reference/java/security/KeyStore#setEntry(java.lang.String,%20java.security.KeyStore.Entry,%20java.security.KeyStore.ProtectionParameter)) method. To proceed further I need to check that how is the EC key pair stored within KMM.jar (e.g., PEM, DER, JKS, custom format)? Once that is clear the next step would be to separate out the public and private key from the generated EC key pair and load that into the android keystore under the app alias. The retrieval method is already implemented.

**Comment by GuyPhy** [comment]
Updated the PR associated with code. Pending actions are:
- Resolve build error 
```
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 3 files found with path 'META-INF/versions/9/OSGI-INF/MANIFEST.MF' from inputs:
      - /Users/guyphy4/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcpkix-jdk18on/1.78.1/17b3541f736df97465f87d9f5b5dfa4991b37bb3/bcpkix-jdk18on-1.78.1.jar
      - /Users/guyphy4/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcutil-jdk18on/1.78.1/5353ca39fe2f148dab9ca1d637a43d0750456254/bcutil-jdk18on-1.78.1.jar
      - /Users/guyphy4/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk18on/1.78.1/39e9e45359e20998eb79c1828751f94a818d25f8/bcprov-jdk18on-1.78.1.jar
     Adding a packagingOptions block may help, please refer to
     https://developer.android.com/reference/tools/gradle-api/8.1/com/android/build/api/dsl/ResourcesPackagingOptions
     for more information
```
- Test code for functionality
- Handle exception chain more efficiently.

**Comment by GuyPhy** [comment]
Updated code in associated PR
The error signature associated with storing keys at the moment is
```
Error:  [Error: Problem: Failed to store private key]
```

With the error code `E keystore2:     Error::Km(ErrorCode(-1000))`

This generally means that either the key format we are trying to store in hardware secure element is not compatible or there is a clashing alias for the key being stored.
